# Site settings
title: Bitfox
email: info@bitfox.com
description: > # this means to ignore newlines until "baseurl:"
  Bitfox is a web development agency based in Fredericton, NB focused on developing web solutions that work for you.
baseurl: ""
url: "http://www.bitfox.com"

# Build settings
markdown: kramdown
