text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic nobis, consectetur explicabo.'

services:
- icon: 'web'
  title: 'Websites'
  description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam minima asperiores tempora quae, accusamus corporis aperiam incidunt aliquam maiores, soluta quo, sed, ullam illum quibusdam pariatur adipisci repudiandae nemo aliquid.'
- icon: 'stay_current_portrait'
  title: 'Web & Mobile Applications'
  description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam minima asperiores tempora quae, accusamus corporis aperiam incidunt aliquam maiores, soluta quo, sed, ullam illum quibusdam pariatur adipisci repudiandae nemo aliquid.'
- icon: 'invert_colors'
  title: 'Branding & Design'
  description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam minima asperiores tempora quae, accusamus corporis aperiam incidunt aliquam maiores, soluta quo, sed, ullam illum quibusdam pariatur adipisci repudiandae nemo aliquid.'